# crossover parameters
CHOOSE_ANOTHER_GENE_PROBABILITY = 0.5  # default 0.5
DISABLE_GENE_PROBABILITY = 0.75  # default 0.75

# mutations parameters
MUTATE_WEIGHT_PROBABILITY = 0.2
ADD_NODE_PROBABILITY = 0.01
ADD_CONNECTION_PROBABILITY = 0.08
CROSSOVER_PROBABILITY = 0.75

# species division parameters
COMPATIBILITY_THRESHOLD = 0.5
EXCESS_GENE_COEFF = 2
DISJOINT_GENE_COEFF = 2
AVERAGE_WEIGHT_DIFF_COEFF = 1
MIN_GENOME_LENGTH = 20

# selection parameters
MAX_STALENESS = 20
