# crossover parameters
CHOOSE_ANOTHER_GENE_PROBABILITY = 0.5  # default 0.5
DISABLE_GENE_PROBABILITY = 0.75  # default 0.75

# mutations parameters
MUTATE_WEIGHT_PROBABILITY = 0.7
RESET_WEIGHT_PROBABILITY = 0.05
ADD_NODE_PROBABILITY = 0.003
ADD_CONNECTION_PROBABILITY = 0.001
CROSSOVER_PROBABILITY = 0.75

# species division parameters
COMPATIBILITY_THRESHOLD = 1.5
EXCESS_GENE_COEFF = 1
DISJOINT_GENE_COEFF = 1
AVERAGE_WEIGHT_DIFF_COEFF = 0.5
MIN_GENOME_LENGTH = 20

# selection parameters
MAX_STALENESS = 20
